global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      10s

scrape_configs:
  - job_name: 'windvane'
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /data.txt
    static_configs:
      - targets: ['192.168.192.102:80']

  - job_name: 'datalogger'
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.192.101:80']
