version: "3.3"
services:
  prometheus:
    hostname: prometheus
    image: "ghcr.io/danopstech/prometheus:latest"
    restart: always
    user: "root"
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: /docker/prometheus/config/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: /docker/prometheus/data
        target: /prometheus

  grafana:
    hostname: grafana
    image: "ghcr.io/danopstech/grafana:latest"
    restart: always
    user: "root"
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=ae3e-plotly-panel
      - GF_LOG_CONSOLE_LEVEL=warn
    volumes:
      - type: bind
        source: /docker/grafana/data
        target: /var/lib/grafana
      - type: bind
        source: /docker/grafana/conf
        target: /etc/grafana/
