# Generated by Django 4.0.6 on 2022-07-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('item', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('item',),
            },
        ),
    ]
