---
- name: Configure localhost to support Marine Logger
  hosts: marinelogger
  connection: local
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Perform upgrade
      apt:
        autoclean: yes
        autoremove: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 

    - name: Install required packages
      apt:
        autoclean: yes
        autoremove: yes
        name: [
          vim,
          python3-serial,
          python3-smbus,
          minicom,
          python3-rpi.gpio,
          i2c-tools,
          libi2c-dev,
        ]

    - name: Enable I2C
      lineinfile:
        line: dtparam=i2c_arm=on
        insertafter: "^#dtparam=i2c_arm=on"
        state: present
        path: /boot/config.txt

    - name: Disable console redirection to python3-serial
      copy:
        content: "root={{ ansible_facts['ansible_cmdline']['root'] }} rootfstype=ext4 fsck.repair=yes rootwait"
        dest: /boot/cmdline.txt
        mode: 0755
        owner: root
        group: root




# Tasks
# - add pi to tty group
