---
- name: Configure localhost to support Marine Logger
  hosts: marinelogger
  connection: local
  become: yes
  become_method: sudo
  become_user: root

  vars:
    - dest_dir: /home/pi
    - grove_dir: "{{ dest_dir }}/GrovePi"

  tasks:
    - name: Perform upgrade
      apt:
        autoclean: yes
        autoremove: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 

    - name: Install required packages
      apt:
        autoclean: yes
        autoremove: yes
        name: [
          vim,
          python3-serial,
          python3-smbus,
          minicom,
          python3-rpi.gpio,
          i2c-tools,
          libi2c-dev,
          avrdude,
        ]

    - name: Enable I2C
      lineinfile:
        line: dtparam=i2c_arm=on
        insertafter: "^#dtparam=i2c_arm=on"
        state: present
        path: /boot/config.txt

    - name: Disable console redirection to python3-serial
      copy:
        content: "root={{ ansible_facts['cmdline']['root'] }} rootfstype=ext4 fsck.repair=yes rootwait"
        dest: /boot/cmdline.txt
        mode: 0755
        owner: root
        group: root

    - name: Clone recent GrovePi repository
      git:
        repo: https://github.com/DexterInd/GrovePi.git
        dest: "{{ grove_dir }}"
        clone: yes
        update: yes
        force: yes
      delegate_to: localhost
      become: no

    - name: Upgrade GroupePi firmware
      shell:
        cmd: "echo y | {{ grove_dir }}/Firmware/firmware_update.sh"
        chdir: "{{ grove_dir }}/Firmware/"

    - name: Install Dexter software
      shell:
        cmd: "bash {{ grove_dir }}/Script/update_grovepi.sh --system-wide --no-update-aptget --bypass-gui-installation"
        chdir: "{{ grove_dir }}/Firmware/"
      delegate_to: localhost
      become: no




# Tasks
# - add pi to tty group
